vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        carte_image:
            uri_prefix: /images/carte
            upload_destination: '%kernel.project_dir%/public/images/carte'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
